# Standard Library


## Question 1 

Practice with creating functions. In the first step I will define a list with several numbers. In the second I will write a function that uses that list to output several numbers. (The min, max, and average).

In [26]:
my_list = [5, 8, 10]

In [27]:
print(min(my_list), max(my_list), sum(my_list)/3)

5 10 7.666666666666667


## Question 2

In the first excerices I test if various types of variables are mutable (they can be overwritten) or immutable. 
To do this I first create the variable, make a copy of the variable, make changes to the variable, and then test if 
the original variable and the copy are the same. If they are mutable meaning the original changed with the copy, 
then the message "True" will be displayed. If the variable is immutable, the message "False" will be displayed. 

### Numbers

In [2]:

num = 5
num2 = num
num2 = num2 + 1
num2 == num

False

In [3]:
print(num2, num)

6 5


Numbers are immutable

### Names

In [6]:
name = 'Alex'
name2 = name
name2 = name2 + 'a'
name2 == name

False

In [7]:
print (name, name2)

Alex Alexa


Names are immutable

### Lists 

In [12]:
list = [1, 2, 3]
list2 = list
list2.append(1)
list2 == list

True

In [13]:
print(list, list2)

[1, 2, 3, 1] [1, 2, 3, 1]


Lists are mutable

### Tuples

In [19]:
new_tuple = (5, 6, 7)
new_tuple2 = new_tuple
new_tuple2 = new_tuple2 + (1,)
new_tuple == new_tuple2

False

In [20]:
print (new_tuple, new_tuple2)

(5, 6, 7) (5, 6, 7, 1)


Tuples are immutable

### Dictionaries

In [22]:
class_dict = {'econ1': 'tools', 'econ2': 'publicfinance'}
class2_dict = class_dict
class2_dict[1] = 'a'
class_dict == class2_dict

True

In [23]:
print (class_dict, class2_dict)

{'econ1': 'tools', 'econ2': 'publicfinance', 1: 'a'} {'econ1': 'tools', 'econ2': 'publicfinance', 1: 'a'}


Dictionaries are mutable

## Question 3

For this question I wrote a module called "calculator.py". I will first run and import the module which should return no results. I will then write a functon that uses the calculator module to calculate the length of the hypotenuse of a right triangle. 

In [29]:
import calculator

In [30]:
run calculator

In [31]:
g = lambda x, y: sqrt((sum(prod(x,x), prod(y,y))))

In [32]:
g(2, 4)

4.47213595499958

# Introduction to NumPy

## Question 1

In these next questions I practice creating matrices and performing various operations. In this question, I define 2 matrices A and B, and return the matrix product. First I have to import the NumPy package. 

In [34]:
import numpy as np

In [36]:
A = np.array([[3, -1, 4], [1, 5, -9]])

In [37]:
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])

In [39]:
print (A)

[[ 3 -1  4]
 [ 1  5 -9]]


In [40]:
print (B)

[[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3 -2 -3]]


In [41]:
np.dot(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Question 2 

A demonstration of the Cayle-Hamilton Theorem

In [42]:
A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
print(A)

[[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]


In [43]:
B = np.dot(A, A)
print(B)

[[-10  20  25]
 [-37  53  58]
 [-17  13   8]]


In [44]:
C = np.dot(B, A)
print(C)

[[-135  165  165]
 [-348  402  387]
 [ -78   72   57]]


In [45]:
D = -C + (9 * B) - (15 * A)

In [46]:
print (D)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Question 5

Defiine 3 matrices and use the stacking function to create and return a block matrix. 

In [47]:
A = np.array([[0, 2, 4], [1, 3, 5]])
print(A)

[[0 2 4]
 [1 3 5]]


In [48]:
B = np.array([[3, 0 ,0], [3, 3, 0], [3, 3, 3]])
print (B)

[[3 0 0]
 [3 3 0]
 [3 3 3]]


In [49]:
C = np.array([[-2, 0, 0], [0, -2, 0], [0, 0, -2]])
print (C)

[[-2  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [50]:
AT = np.transpose(A)
print (AT)

[[0 1]
 [2 3]
 [4 5]]


In [51]:
A_0 = np.zeros((3,3))
print (A_0)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [52]:
I = np.eye(3)
print (I)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [54]:
B_1 = np.zeros((2, 2))
print(B_1)

[[ 0.  0.]
 [ 0.  0.]]


In [55]:
B_2 = np.zeros((2, 3))
print (B_2)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [56]:
C_2 = np.zeros((3, 2))
print (C_2)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [57]:
a = np.hstack((A_0, AT, I))
print(a)

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]]


In [58]:
b = np.hstack((A, B_1, B_2))
print (b)

[[ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]]


In [59]:
c = np.hstack((B, C_2, C))
print(c)

[[ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


In [60]:
F = np.vstack((a, b, c))
print (F)

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


# OOP 

## Question 1

In the first question I expand upon the example in the book so that my "Backpack" also accepts a color and 5 items. 
I have created a warning so that if I try to put more than 5 items in my backpack it will say "No Room!". 
At the end of the exercise I will reset the contents of the backpack using the dump command I have created. In the next line I import my class code. 
    

In [457]:
from oop import Backpack

I will now name my backpack and give it a color. 

In [458]:
my_backpack = Backpack("Alex", "red")

In [459]:
my_backpack.name

'Alex'

In [460]:
my_backpack.color

'red'

Now I will add items to my backpack.

In [461]:
my_backpack.put("computer")

In [462]:
my_backpack.contents

['computer']

I have successfully added 1 item (computer) to my backpack. I will now continue to add more items.

In [463]:
my_backpack.put("notebook")
my_backpack.put("pens")
my_backpack.put("calculator")
my_backpack.put("snacks")

In [464]:
my_backpack.put("jacket")

No Room!


In [465]:
my_backpack.contents

['computer', 'notebook', 'pens', 'calculator', 'snacks']

I have succesfully added 5 items to my backpack. When trying to add a jacket, I received the error message "No Room!" 
because the maximum size of the backpack is 5. I will now clear the contents of the backpack. 

In [466]:
my_backpack.dump()

In [467]:
my_backpack.contents

[]

## Question 2

In this excercise I will create a Jetpack class that inherits from the Backpack class I have just created. The default size is now 2 and my class has a few attributes (fuel and fly). The amount of fuel I start with is 10. When I try to fly for a minute, I will decrease the amount of fuel available by .15. If I try to fly for longer than my fuel would last, I should receive the error message "Not enough fuel!". Otherwise, I will be notified of how much fuel I have left. I will now import my Jetpack class. 

In [482]:
from oop import Jetpack

I will now name my Jetpack

In [483]:
my_jetpack = Jetpack("alex", "blue")

In [484]:
my_jetpack.name

'alex'

In [485]:
my_jetpack.color

'blue'

In [486]:
my_jetpack.fuel

10

I will now add an item to my Jetpack by using the put command defined in the Backpack class.

In [473]:
my_jetpack.put("parachute")

In [474]:
my_jetpack.contents

['parachute']

I will now try to "fly" for 10 minutes. 

In [475]:
my_jetpack.fly(10)

8.5

I have enought fuel to fly for 10 minutes. After my flight I will have 8.5 left. Since I was able to do that, I will try to fly for a little over an hour. Let's say 67 minutes.

In [476]:
my_jetpack.fly(67)

Not enough fuel!


I am unable to take that long of a flight because I will not have enough fuel to make it. I will now clear out my jetpack and the amount of fuel. 

In [478]:
my_jetpack.dump()

In [479]:
my_jetpack.contents

[]

In [480]:
my_jetpack.fuel

0